### ISSUE TITLE
Add optional target volume id parameter

### ISSUE THREAD

**Issue by oriyarde** [csi-addons/spec#21]
for all RPCs:
in addition to the existing `volume_id`, which represents the source volume, add a `target_volume_id` parameter, which represents an existing (but new) target volume.

**Comment by ShyamsundarR** [comment]
NOTE: This is just a broad initial thought, there are a lot of details to tease apart, hence read with caution

I would like to look at the spec change more aligned with a future VolumeReplicationHandle based operation as follows,

- Add a CSI capability to denote if provider requires a target VolumeReplicationHandle or not
```
CSI VRTarget Capability:
  - UNKNOWN|REQUIRED|AUTO
```

- Update VR spec to take in a target handle for replication
- Respond with a VRHandle for a created VolumeReplcation, as a target handle
- NOTE:
  - It is assumed that if fan out replication is desired, the same VRHandle can be used across the fan-out clusters, and one per cluster is not required
```
VR:
  Spec:
    - Source: [PVC|VRHandle]
    - Target: [VRHandle]
    - State: [Primary|Secondary]
    - VRClass: <class-name>
  Status:
    - VRHandle
```

- CSI VR add-on API changes to add a target_replication_handle, which is optional based on the CSI capability as above
```
EnableVolumeReplication (
  volume_id
  target_replication_handle
  parameters
  secrets
)
```

- A PVC can be generated using a data source, which is a VR
- NOTE:
  - Hence a VR SHOULD be created prior to a PVC, and be able to determine the storage volume that was replicated
  - This also requires that a VRHandle be available to create the VR, mentioned in its spec.source as above
```
PVC:
  DataSource:
    VolumeReplication
```

### What can be done in the near term

- We could add a volume_replication_handle, instead of a target_volume_id
- The assumption is that this handle is reusable for a fan-out case, and does not need a handle per fan out instance
- How this handle is generated is out of scope for the intermediate change

**Comment by Madhu-1** [comment]
Is this target_replication_handle need to be part of the EnableVolumeReplication request or it should be part of EnableVolumeResponse (as it will be generated by the SP, not by the users who are creating the VolumeReplication objects)?  Do we need to pass the `target_replication_handle` to any of the RPC calls in the exiting cluster?

**Comment by oriyarde** [comment]
I understand the need for a fan out replication to optimize etcd usage, but at least in our storage systems, the volumes must be created before the "replication relationship", and both volume ids are required for the "replication relationship" creation.
and IMO, PVC should be the only k8s object to manage a volume lifecycle.

in addition, from what I saw in regular CSI, they use the term `id` throughout the spec, and use `Handle` only in their sidecar implementations (source code and k8s objects). for consistency, I think the same should be done here.

so I still don't see how we can avoid passing a `target_volume_id` at least for `EnableVolumeReplicationRequest`

**Comment by ShyamsundarR** [comment]
> Is this target_replication_handle need to be part of the EnableVolumeReplication request or it should be part of EnableVolumeResponse (as it will be generated by the SP, not by the users who are creating the VolumeReplication objects)? Do we need to pass the `target_replication_handle` to any of the RPC calls in the exiting cluster?

The handle/id is a response to an enable request, that is correct. A future CreateVolume request can be using the replication handle id as the data source (IOW the VR with a replication _id as the data source).

VR can have 2 sources to enable replication, a PVC (volume_id) or a replicaiton_id (switching to id instead of handle as suggested above).

The volume_id as source enables replication, whereas when presented with a replication_id the CSI storage plugin may only need to "verify" if the id is correct, and set it's state to the desired state (as in call enable|disable apropriately).

The addition of a local volume_id to the enable request with a target replication_id, as part of the enable request is where the meeting point of the 2 variants lie. Hence EnableVolumeReplicationRequest can take an optional volume_id when a replication_id is present to link the two as desired by @oriyarde 

However, the model hence assumes a local volume is created, and passed to VolRep, so VolRep MAY hence have 2 data sources, a local volume_id from a PVC data source, and an additional replication_id from the VR itself (which is created at a remote site and passed to the local site).

The VolRep sidecar reconciler can for the moment pass this to the EnableVolumeReplicaitonRequest and let the storage plugin decide how to use the same, rather than amending the reconcile with the above assimptions and new verbs, which we will get to eventually.

@oriyarde request that the parameter to EnableVolumeReplicationRequest be changed to `replication_id` and passed to EnableVolumeReplicationRequest (and other gRPCs as needed). We will hold that extension as an experimental extension till we can decide on this.

**Comment by ShyamsundarR** [comment]
> I understand the need for a fan out replication to optimize etcd usage, but at least in our storage systems, the volumes must be created before the "replication relationship", since both volume ids are required for the "replication relationship" creation.
> and IMO, PVC should be the only k8s object to manage a volume lifecycle.

PVC is user created, cluster specific, and could even appear due to other constraints like stateful set scaling. VolumeReplication is across clusters, hence it's lifecycle is not necessarily the same as the PVC lifecycle.

The model adopted here is that the storage CSI plugin can communicate with the remote storage instance control plane, and not only with it's data plane. IOW, the responsibility of storage orchestration of the replica is passed onto the storage plugin and not orchestrated by the APIs in k8s control plane. Thus, the volume lifecycle is still controlled by the PVC, for example deleting a PVC (and hence the PV) that is a volume replication primary, would delete the volume and its replicas across the storage instances. It would fail if the storage layers are unable to garbage collect the remote end points due to various unavailability constraints and hence the PV would remain in terminating state from a k8s control plane perspective.

NOTE: Even with the above model, it is understood that reusing the volume_id across storage instances will not work for all storage vendors, and the reason to shift to a replication_id instead.

**Comment by oriyarde** [comment]
> NOTE: Even with the above model, it is understood that reusing the volume_id across storage instances will not work for all storage vendors, and the reason to shift to a replication_id instead.

if I understand you suggestion correctly, as the IBM block storage vendor, I see several issues:

1. there is nothing for us to create before the second PVC is created, so our `Enable/DisableVolumeReplication` would not create/delete (nor enable/disable) anything.
2. as you mentioned, the driver would have to perform actions on both storage sides for a single RPC (e.g. `Create/DeleteVolume`).
3. the user would not be able to remove the "replication relationship" while keeping both volumes.
4. I assume the replication_id would have to contain (/be) the volume id of the "remote" side, which means that for the same "replication relationship", the replication_id would be different, depending on which side the VR instance is created.
5. the replication_id alone could not be used to uniquely identify the "replication relationship", since it would be defined before the second volume and the "replication relationship" are created.
6. the second PV could not be imported from a pre-existing volume, because we would have to create a new volume for each replication (no `CreateVolume` request is issued when importing an existing volume).

let me know if you want to discuss more about scenarios for any of the above issues, e.g.:
- issue number 2: disaster recovery/topology constraints
- issue number 3: "remote clone"/migration without deletion
- issue number 6: physically transferring a volume disk, to reduce the data diff (for a quicker initial sync)

we wouldn't want to impede with a shift that works for other vendors, but I would not recommend it to be a requirement for all vendors.

**Comment by ShyamsundarR** [comment]
> @oriyarde request that the parameter to EnableVolumeReplicationRequest be changed to `replication_id` and passed to EnableVolumeReplicationRequest (and other gRPCs as needed). We will hold that extension as an experimental extension till we can decide on this.

@oriyarde are we making this naming change?

**Comment by ShyamsundarR** [comment]
> > NOTE: Even with the above model, it is understood that reusing the volume_id across storage instances will not work for all storage vendors, and the reason to shift to a replication_id instead.
> 
> if I understand you suggestion correctly, as the IBM block storage vendor, I see several issues:
> 
>     1. there is nothing for us to create before the second PVC is created, so our `Enable/DisableVolumeReplication` would not create/delete (nor enable/disable) anything.

In the model we do not pass the creation of the PVC on the remote k8s cluster to the user. The storage plugin is expected to be peered with its remote at the control plane layer, and hence can create the required volume at the remote "storage" cluster, enable replication, return a `replication_id` that the user needs to take to the remote k8s cluster to create a VolRep resource from the same, and then pass this VolRep resource as the DataSource for the PVC request (for failover/relocate requirements).

> 
>     2. as you mentioned, the driver would have to perform actions on both storage sides for a single RPC (e.g. `Create/DeleteVolume`).

Yes.

> 
>     3. the user would not be able to remove the "replication relationship" while keeping both volumes.

Deleting VolumeReplication as Primary, disables the replication and should garbage collect the remote volume as well. This is the specification at present.

We may want to provide a `state` to break the replica relationship, and hence retain the remote volume and the local volume. Access to the remote volume (as there is no PVC) would be via the VolRep(with replication_id) on remote -> PVC (with VolRep as data source) -> provisioned.

But, the lifecycle of a broken replication volume is further determined by the user.

As is evident this needs more thought, on how the user would interact with the same and what are the storage plugin responsibilities here.

> 
>     4. I assume the replication_id would have to contain (/be) the volume id of the "remote" side, which means that for the same "replication relationship", the replication_id would be different, depending on which side the VR instance is created.

Yes, at present for the IBM block storage that would be correct. We need to see how we can reconcile this either-way in the future. I.e a generic ID can also be returned, and reused across the source and the target.

The above is not a requirement at present for the spec change PR, rather currently we just rename this to a `replication_id` and then IBM block storage would pass the target_volume_id in this field, as we resolve who is responsible for control plane actions across the storage peers.

> 
>     5. the replication_id alone could not be used to uniquely identify the "replication relationship", since it would be defined before the second volume and the "replication relationship" are created.

I think above process outlines why this need not be the case?

> 
>     6. the second PV could not be imported from a pre-existing volume, because we would have to create a new volume for each replication (no `CreateVolume` request is issued when importing an existing volume).

The import would be via a DataSource, which would be a VolumeReplication object in the future.

> 
> 
> let me know if you want to discuss more about scenarios for any of the above issues, e.g.:
> 
>     * issue number 2: disaster recovery/topology constraints
> 
>     * issue number 3: "remote clone"/migration without deletion
> 
>     * issue number 6: physically transferring a volume disk, to reduce the data diff (for a quicker initial sync)
> 
> 
> we wouldn't want to impede with a shift that works for other vendors, but I would not recommend it to be a requirement for all vendors.

The core here is that storage vendor plugins are peered with their control planes as well, to take actions as required.

Future requirements such as:
- Transferring k8s snapshots for use across storage
- Addressing volumes added to a VoluemGroup and hence a VolumeReplication created for the volume group should pick up newer volumes and replicate the same
- Resize differences between the source and the target, and reconcile them at the storage plugin layers

Are better addressed if the storage clusters address the required operations across its peers using its control plane.

**Comment by oriyarde** [comment]
> > @oriyarde request that the parameter to EnableVolumeReplicationRequest be changed to `replication_id` and passed to EnableVolumeReplicationRequest (and other gRPCs as needed). We will hold that extension as an experimental extension till we can decide on this.
> 
> @oriyarde are we making this naming change?

are you sure this is the best approach? passing a `target_volume_id` to EnableVolumeReplication makes more sense to me than passing a `replication_id`, because a replication id cannot exist before the replication exist

**Comment by ShyamsundarR** [comment]
> > > @oriyarde request that the parameter to EnableVolumeReplicationRequest be changed to `replication_id` and passed to EnableVolumeReplicationRequest (and other gRPCs as needed). We will hold that extension as an experimental extension till we can decide on this.
> > 
> > 
> > @oriyarde are we making this naming change?
> 
> are you sure this is the best approach? passing a `target_volume_id` to EnableVolumeReplication makes more sense to me than passing a `replication_id`, because a replication id cannot exist before the replication exist (which is the 5th issue I mentioned).
> 
> IOW, if we pass a value which we call `replication_id` to EnableVolumeReplication, by design, it cannot uniquely identify a "replication relationship" by itself, which is why I think this value should not be named `replication_id`

The case, once we progress on this further would be:
- Create VolumeReplication resource with a PVC DataSource, and as a response receive a `replication_id`
- Use that `replication_id` as the source in an alternate cluster instead of a PVC as the Datasource for a VolumeReplication resource
- Create a PVC from the VolumeReplication resource as its DataSource

So it is true that we cannot create a `replication_id` without initially creating a VolumeReplication resource as you state.

For now, in the IBM block storage, the `replication_id` is the target `volume_id`, which is hence created by simply creating a PVC at the target (as is the case in the current scheme laid out by you).

I want to avoid calling this a target_`volume_id` at present, as that makes is a volume id and hence assumes there is already a volume created at the remote site, forcing the model to assume (at least in language) that replication is between 2 PVC is 2 different sites.

**Comment by oriyarde** [comment]
> assumes there is already a volume created at the remote site, forcing the model to assume (at least in language) that replication is between 2 PVC is 2 different sites.

but this is exactly what happens in our case, and it doesn't contradict the model of VR as dataSource that you described - we can still add in the future a `replication_id` in EnableVolumeReplicationResponse for use in the non-Enable RPCs, but passing a parameter called `replication_id` to EnableVolumeReplication will not make sense at any point in time (for any vendor)

**Comment by ShyamsundarR** [comment]
> > assumes there is already a volume created at the remote site, forcing the model to assume (at least in language) that replication is between 2 PVC is 2 different sites.
> 
> but this is exactly what happens in our case, and it doesn't contradict the model of VR as dataSource that you described - we can still add in the future a `replication_id` in EnableVolumeReplicationResponse for use in the non-Enable RPCs, but passing a parameter called `replication_id` to EnableVolumeReplication will not make sense at any point in time (for any vendor)

I am not convinced that PVC lifecycle across clusters should be a user responsibility, and hence adding a `target_volume_id` is not a long term option for the spec IMHO. We can discuss this and I can correct myself, and we can adapt to some form of hybrid model.

In the meantime, I am convinced about the use of `replication_id` as a more longer term solution, hence as an interim measure, **in the interest of time**, I am suggesting that you use this field to pass the target volume_id, instead of us introducing `replication_id` and also supporting `target_volume_id` in the future.

I agree that passing this to enableVolumeReplication does not make sense (we (@Madhu-1 and me) discussed this). I am attempting to keep the spec as is, and we are IMO making exceptions to the gRPC to pass fields that may be useless for now. BUT we do not have other APIs to get this going, so again we do something that works in the really short term, and not have to support a workaround (either way `replication_id` or `target_volume_id`) in the longer term.

As we are not reaching a conclusion, changing and supporting a spec in the long term for something we add in haste is always a maintenance problem.

**Comment by oriyarde** [comment]
> we do something that works in the really short term, and not have to support a workaround (either way `replication_id` or `target_volume_id`) in the longer term.

so is `target_volume_id` just as fine as `replication_id` for now?

**Comment by ShyamsundarR** [comment]
> > we do something that works in the really short term, and not have to support a workaround (either way `replication_id` or `target_volume_id`) in the longer term.
> 
> so is `target_volume_id` just as fine as `replication_id` for now?

Maybe I should keep my comments terse. I would prefer you use `replication_id` instead of `target_volume_id` for this change.

**Comment by oriyarde** [comment]
OK, I opened https://github.com/csi-addons/spec/pull/23.
closing this issue
