### ISSUE TITLE
Add Mergify to this project

### ISSUE THREAD

**Issue by Madhu-1** [csi-addons/spec#3]
Configure mergify to auto-merge the PR when CI is passing and PR is having the required approvals.

details about  mergify at https://github.com/Mergifyio/mergify-engine

**Comment by nixpanic** [comment]
I am happy to look into this. What kind of rules for approval should be considered?

- is there a (GitHub) team of members that are required for reviewing PRs?
- could PRs be labelled as `documentation` so that fewer reviews are needed?
- passing all current available CI jobs are a requirement before merging

**Comment by Madhu-1** [comment]
> I am happy to look into this. What kind of rules for approval should be considered?
> 

Thanks @nixpanic 

> * is there a (GitHub) team of members that are required for reviewing PRs?

Currently, we don't have separate team for this one, i can create one for the core spec reviews

> * could PRs be labelled as `documentation` so that fewer reviews are needed?

Yes it's acceptable as it's just a doc change

> * passing all current available CI jobs are a requirement before merging

Yes, we need to make sure the current CI job passes to merge it. 

below is the criteria I was looking at

* All CI passes
* Has required approval from team
* atleast 2 approvals for any  spec change

**Comment by humblec** [comment]
>could PRs be labelled as documentation so that fewer reviews are needed?

May be design instead of documentation make sense @nixpanic @Madhu-1
